name: bcancer-gnn
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - streamlit
    - pandas
    - numpy
    - networkx
    - plotly
    - torch==2.0.1
    - torch-scatter
    - kaleido
